title: Docs Theme
description: "This series of workshops will give you hands-on experience working with Azure Cosmos DB using the SQL API, JavaScript and .NET Core SDK."
repository: azure-immersion/cosmos-jekyll-theme
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
sass:
  style: :compressed